# Setup
title:        Next Generation Biologists
tagline:      BBSRC STARS-funded bioinformatics workshops at Universities of Leeds and Huddersfield
baseurl:      ""
url:		  "http://nextgenbiologists.org"
paginate:     1

# About/contact
author:
  name:       Jarek Bryk
  url:        http://nextgenbiologists.org

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
